### ISSUE TITLE
search multiple keywords in a document and return the snippet which contains the specific keywords in another document.

### ISSUE THREAD

**Issue by Veronica15rexin** [Veronica15rexin/infinity#1]
For example:
the input is inputfile.docx
task is to read the inputfile and search for multiple keywords. Say so, keywords=("red","property","unique",....)
the output is outputfile.docx
The outputfile should contain the paragraph in which the keywords are present.

**Comment by Veronica15rexin** [comment]
@JorjMcKie

**Comment by JorjMcKie** [comment]
Hi,
I am a little confused about in what area your problem actually is.
If it is really Python, the solution of your case is not a big deal:
1. Walk through the text blocks of input file.
2. For each block check whether all keywords occur in it.
3. If yes, write block to output file.

Point 2. could be inplemented like so:
```python
text = ... # text inside the block
valid = True # will be true if all keywords occur
for kw in keywords:
    if kw not in text:
        valid = False
        break
if valid:
    # write this block text to output file
```
Simple enough!

The more difficult part is how to deal with the file format. You mentioned file extension `.docx` which is MS Word. This requires you must make yourself acquainted with manipulating Word documents programmatically.
The most adequate language for this is VBA (visula basic) - not Python. However there are Python packages which create a connection to MS Office documents I remember faintly.

Or you first convert the word document to PDF, and then use PyMuPDF to implement your intention. Here also the question is, what type of output you would need ... PDF? Plain text?

**Comment by Veronica15rexin** [comment]
Hi, Thanks for the reply. Let me explain in a bit more detail. Here's the code which I tried.
import docx
import aspose.words as aw
doc = aw.Document()
builder = aw.DocumentBuilder(doc)
def getText(filename):
    count = 0
    doc = docx.Document(filename)
    fullText = []
    for para in doc.paragraphs:
        if len(para.text) > 3:
            fullText.append(para.text)
    return fullText
text = getText('input.docx')
for i in range(len(text)):
    text[i] = text[i].lower()
   
string=input()
for i, line in enumerate(text):
    if string in line:
        print(line)
        builder.write(line)
        doc.save("output.docx")
By running this code, I'm able to extract the snippet and write the output to the word document.
Here I'm able to pass only a single keyword. But what I wanted actually is to pass multiple keywords and extract the line/paragraph and write it to any form of output(docx/pdf/text). And another major thing is if a word contains a table this code does not capture the content present inside the table whereas the below code does.
from PyPDF2 import PdfFileReader, PdfFileWriter
file_path = 'input.pdf'
pdf = PdfFileReader(file_path)
with open('extractpdf_to_text.txt', 'w') as f:
    for page_num in range(pdf.numPages):
        pageObj = pdf.getPage(page_num)
        try:
            txt = pageObj.extractText()
            print(''.center(100, '-'))
        except:
            pass
        else:
            f.write('Page {0}\n'.format(page_num+1))
            f.write(''.center(100, '-'))
            f.write(txt)
    f.close()
searchfile = open("extractpdf_to_text.txt", "r")
string=input()
for line in searchfile:
    if string in line: print(line)
searchfile.close()
Is this data relevant enough? @JorjMcKie

**Comment by JorjMcKie** [comment]
> Here I'm able to pass only a single keyword.

This is because you do not do a check like I suggested in my previous post. For every block of text you must walk through every single word of the keywords.

> contains a table this code does not capture ...

This is because Word does not treat a table like a paragraph. This requires more logic from you: collect **_all_** table content first and then treat the combined text as a paragraph.
PDF does not know the heck about tables: it treats them all like normal text. So the behaviour in this context is different.

As per keyword containment, the most natural way to this in Python is using **_sets_**:
```python
keywords = set(keywords)
blockwords = set(text.split())
if keywords <= blockwords:
    # all keywords occurring in block!
```

**Comment by Veronica15rexin** [comment]
import PyPDF4
import re
import os
import pandas as pd
import shutil
os.getcwd()

String = input()

lis=[]
path=[]
c=[]
a=[]
z=[]
for r , d ,f in os.walk(os.getcwd()+"//Test Input"):
    for i in f:
         if i.lower().endswith('.pdf'):
                print(i)
                lis .append(i)
                path.append(os.path.join(r,i))
                for s in path:
                    #s.RemoveSecurity()
                    object = PyPDF4.PdfFileReader(s)#strict=False
                    
                    #if object.isEncrypted:
                        #object.decrypt('')
                        
                    NumPages = object.getNumPages()
                    for k in range(0, NumPages):
                        PageObj = object.getPage(k)
                        try:
                            Text = PageObj.extractText()
                            ResSearch = re.search(String.lower(), Text.lower())
                            print(ResSearch,k)
                            a.append(ResSearch)
                            if ResSearch !=None:
                                z.append(k+1)
                                c.append(s)
                        except:
                            if(Text == ""):
                                Text = textract.process(f, method='tesseract', encoding='utf8')
g=[]
[g.append(i.split("\\")[-1]) for i in c]
c=g
data = {'Page_no':z,
        'PDF_name':c}
 

df = pd.DataFrame(data)
df.drop_duplicates(inplace=True)
df=df.reset_index()
df.drop("index",axis=1,inplace=True)

df

This is the code I've developed which reads 'n' number of pdf's and perform search, and returns you a page number and the pdf names which contains a search string. 
I need help to search multiple keywords.

**Comment by Veronica15rexin** [comment]
@JorjMcKie Could you help on this.

**Comment by Veronica15rexin** [comment]
@ItsSiddharth- Could you help on this.

**Comment by Veronica15rexin** [comment]
@ItsSiddharth
